import type { Address, CustomerProfile, Order, Shop } from "@/types";

function paper(
  id: string,
  name: string,
  enabled: boolean,
  bwPrice: number,
  colorPrice: number,
  colorEnabled = true,
) {
  return {
    id,
    name,
    enabled,
    bwEnabled: true,
    bwPrice,
    colorEnabled,
    colorPrice,
    single: true,
    double: true,
  };
}

export const seedShops: Shop[] = [
  {
    id: "shop-sri-digital",
    name: "Sri Digital Xerox",
    ownerName: "Ramesh Kumar",
    phone: "+91 98431 22110",
    email: "sridigital@ordermyxerox.in",
    address: "12, Gandhi Street, Gandhipuram, Coimbatore - 641012",
    hours: "Mon – Sat · 8:00 AM – 9:00 PM",
    rating: 4.8,
    distanceKm: 1.2,
    prepMinutes: 20,
    pickup: true,
    paperTypes: [
      paper("a4", "A4 Paper", true, 2, 10),
      paper("a3", "A3 Paper", true, 4, 18),
      paper("bond", "Bond Sheet", true, 3, 12),
      paper("photo", "Photo Sheet", false, 15, 30),
      paper("glossy", "Glossy Paper", false, 12, 25),
      paper("matte", "Matte Paper", true, 8, 20),
    ],
    printTypes: { bw: true, color: true },
    printSides: { single: true, double: true },
    orientation: { portrait: true, landscape: true },
    binding: [
      { id: "spiral", name: "Spiral Binding", enabled: true, price: 40 },
      { id: "soft", name: "Soft Binding", enabled: true, price: 70 },
      { id: "hard", name: "Hard Binding", enabled: false, price: 180 },
    ],
    additional: [
      { id: "lamination", name: "Lamination", enabled: true, price: 10, perPage: true },
      { id: "stapling", name: "Stapling", enabled: true, price: 5 },
    ],
    delivery: {
      enabled: true,
      fee: 30,
      freeAbove: 500,
      etaMinutes: "30 – 45 minutes",
      areas: ["Gandhipuram", "R.S. Puram", "Peelamedu", "Saibaba Colony"],
    },
    payments: {
      full: true,
      advance: true,
      cashPickup: true,
      cashDelivery: true,
      advanceType: "fixed",
      advanceValue: 50,
    },
  },
  {
    id: "shop-annai-prints",
    name: "Annai Prints & Stationery",
    ownerName: "Lakshmi Narayanan",
    phone: "+91 99406 78120",
    email: "annaiprints@ordermyxerox.in",
    address: "7A, Cross Cut Road, Coimbatore - 641045",
    hours: "Mon – Sun · 9:00 AM – 10:00 PM",
    rating: 4.6,
    distanceKm: 2.4,
    prepMinutes: 30,
    pickup: true,
    paperTypes: [
      paper("a4", "A4 Paper", true, 1.5, 9),
      paper("a3", "A3 Paper", false, 4, 18),
      paper("bond", "Bond Sheet", true, 2.5, 11),
      paper("photo", "Photo Sheet", true, 14, 28),
      paper("glossy", "Glossy Paper", true, 12, 24),
      paper("matte", "Matte Paper", false, 8, 20),
    ],
    printTypes: { bw: true, color: true },
    printSides: { single: true, double: false },
    orientation: { portrait: true, landscape: false },
    binding: [
      { id: "spiral", name: "Spiral Binding", enabled: true, price: 35 },
      { id: "soft", name: "Soft Binding", enabled: false, price: 70 },
      { id: "hard", name: "Hard Binding", enabled: true, price: 160 },
    ],
    additional: [
      { id: "lamination", name: "Lamination", enabled: true, price: 12, perPage: true },
      { id: "stapling", name: "Stapling", enabled: false, price: 5 },
    ],
    delivery: {
      enabled: false,
      fee: 25,
      freeAbove: null,
      etaMinutes: "45 – 60 minutes",
      areas: [],
    },
    payments: {
      full: true,
      advance: true,
      cashPickup: true,
      cashDelivery: false,
      advanceType: "percent",
      advanceValue: 30,
    },
  },
  {
    id: "shop-campus-copy",
    name: "Campus Copy Centre",
    ownerName: "Arun Prasad",
    phone: "+91 90035 41267",
    email: "campuscopy@ordermyxerox.in",
    address: "Opp. PSG College Gate, Peelamedu, Coimbatore - 641004",
    hours: "Mon – Sat · 7:30 AM – 8:30 PM",
    rating: 4.9,
    distanceKm: 3.1,
    prepMinutes: 15,
    pickup: true,
    paperTypes: [
      paper("a4", "A4 Paper", true, 1.8, 8),
      paper("a3", "A3 Paper", true, 3.5, 16),
      paper("bond", "Bond Sheet", false, 3, 12),
      paper("photo", "Photo Sheet", false, 15, 30),
      paper("glossy", "Glossy Paper", false, 12, 25),
      paper("matte", "Matte Paper", false, 8, 20),
    ],
    printTypes: { bw: true, color: true },
    printSides: { single: true, double: true },
    orientation: { portrait: true, landscape: true },
    binding: [
      { id: "spiral", name: "Spiral Binding", enabled: true, price: 30 },
      { id: "soft", name: "Soft Binding", enabled: true, price: 60 },
      { id: "hard", name: "Hard Binding", enabled: false, price: 180 },
    ],
    additional: [
      { id: "lamination", name: "Lamination", enabled: false, price: 10, perPage: true },
      { id: "stapling", name: "Stapling", enabled: true, price: 4 },
    ],
    delivery: {
      enabled: true,
      fee: 20,
      freeAbove: 400,
      etaMinutes: "25 – 40 minutes",
      areas: ["Peelamedu", "Hope College", "Singanallur"],
    },
    payments: {
      full: true,
      advance: false,
      cashPickup: true,
      cashDelivery: true,
      advanceType: "fixed",
      advanceValue: 40,
    },
  },
];

export const seedProfile: CustomerProfile = {
  name: "Tamil Kumaran",
  email: "tamil.k@gmail.com",
  phone: "+91 98765 43210",
};

export const seedAddresses: Address[] = [
  {
    id: "addr-home",
    label: "Home",
    name: "Tamil Kumaran",
    phone: "+91 98765 43210",
    house: "4B",
    street: "Kamaraj Nagar 2nd Street",
    area: "Peelamedu",
    city: "Coimbatore",
    pincode: "641004",
  },
  {
    id: "addr-hostel",
    label: "Hostel",
    name: "Tamil Kumaran",
    phone: "+91 98765 43210",
    house: "Room 212, Sivananda Hostel",
    street: "College Road",
    area: "Gandhipuram",
    city: "Coimbatore",
    pincode: "641012",
  },
];

const now = Date.now();
const ago = (mins: number) => new Date(now - mins * 60000).toISOString();

export const seedOrders: Order[] = [
  {
    id: "OMX-1024",
    customerName: "Tamil Kumaran",
    customerPhone: "+91 98765 43210",
    shopId: "shop-sri-digital",
    shopName: "Sri Digital Xerox",
    documents: [{ id: "d1", name: "Assignment.pdf", pages: 15, sizeMb: 2.4 }],
    config: {
      paperTypeId: "a4",
      printType: "bw",
      side: "double",
      copies: 2,
      pageRangeMode: "all",
      pageRange: "",
      orientation: "portrait",
      bindingId: "spiral",
      additionalIds: [],
    },
    configLabels: {
      paper: "A4 Paper",
      printType: "Black & White",
      side: "Double Side",
      orientation: "Portrait",
      binding: "Spiral Binding",
      additional: [],
    },
    fulfillment: "delivery",
    address: seedAddresses[0]!,
    price: {
      printing: 54,
      binding: 80,
      services: 0,
      delivery: 30,
      discount: 0,
      total: 164,
      billablePages: 30,
    },
    paymentMethod: "advance",
    amountPaid: 50,
    balance: 114,
    paymentStatus: "partial",
    status: "OUT_FOR_DELIVERY",
    createdAt: ago(95),
    updatedAt: ago(8),
    timeline: [
      { status: "NEW", at: ago(95) },
      { status: "ACCEPTED", at: ago(88) },
      { status: "PRINTING", at: ago(70) },
      { status: "FINISHING", at: ago(45) },
      { status: "READY_DELIVERY", at: ago(25) },
      { status: "OUT_FOR_DELIVERY", at: ago(8) },
    ],
  },
  {
    id: "OMX-1023",
    customerName: "Divya Ramesh",
    customerPhone: "+91 91234 56780",
    shopId: "shop-sri-digital",
    shopName: "Sri Digital Xerox",
    documents: [{ id: "d2", name: "Project-Report.pdf", pages: 42, sizeMb: 6.1 }],
    config: {
      paperTypeId: "a4",
      printType: "color",
      side: "single",
      copies: 1,
      pageRangeMode: "all",
      pageRange: "",
      orientation: "portrait",
      bindingId: "soft",
      additionalIds: ["lamination"],
    },
    configLabels: {
      paper: "A4 Paper",
      printType: "Colour",
      side: "Single Side",
      orientation: "Portrait",
      binding: "Soft Binding",
      additional: ["Lamination"],
    },
    fulfillment: "pickup",
    address: null,
    price: {
      printing: 420,
      binding: 70,
      services: 420,
      delivery: 0,
      discount: 46,
      total: 864,
      billablePages: 42,
    },
    paymentMethod: "full",
    amountPaid: 864,
    balance: 0,
    paymentStatus: "paid",
    status: "READY_PICKUP",
    createdAt: ago(160),
    updatedAt: ago(30),
    timeline: [
      { status: "NEW", at: ago(160) },
      { status: "ACCEPTED", at: ago(150) },
      { status: "PRINTING", at: ago(120) },
      { status: "FINISHING", at: ago(60) },
      { status: "READY_PICKUP", at: ago(30) },
    ],
  },
  {
    id: "OMX-1022",
    customerName: "Karthik Selvam",
    customerPhone: "+91 99887 10023",
    shopId: "shop-sri-digital",
    shopName: "Sri Digital Xerox",
    documents: [{ id: "d3", name: "ID-Proof.pdf", pages: 2, sizeMb: 0.4 }],
    config: {
      paperTypeId: "a4",
      printType: "bw",
      side: "single",
      copies: 3,
      pageRangeMode: "all",
      pageRange: "",
      orientation: "portrait",
      bindingId: null,
      additionalIds: ["stapling"],
    },
    configLabels: {
      paper: "A4 Paper",
      printType: "Black & White",
      side: "Single Side",
      orientation: "Portrait",
      binding: "None",
      additional: ["Stapling"],
    },
    fulfillment: "pickup",
    address: null,
    price: {
      printing: 12,
      binding: 0,
      services: 15,
      delivery: 0,
      discount: 0,
      total: 27,
      billablePages: 6,
    },
    paymentMethod: "cash_pickup",
    amountPaid: 0,
    balance: 27,
    paymentStatus: "unpaid",
    status: "NEW",
    createdAt: ago(12),
    updatedAt: ago(12),
    timeline: [{ status: "NEW", at: ago(12) }],
  },
  {
    id: "OMX-1019",
    customerName: "Tamil Kumaran",
    customerPhone: "+91 98765 43210",
    shopId: "shop-campus-copy",
    shopName: "Campus Copy Centre",
    documents: [{ id: "d4", name: "Lab-Record.pdf", pages: 28, sizeMb: 3.2 }],
    config: {
      paperTypeId: "a4",
      printType: "bw",
      side: "single",
      copies: 1,
      pageRangeMode: "all",
      pageRange: "",
      orientation: "portrait",
      bindingId: "spiral",
      additionalIds: [],
    },
    configLabels: {
      paper: "A4 Paper",
      printType: "Black & White",
      side: "Single Side",
      orientation: "Portrait",
      binding: "Spiral Binding",
      additional: [],
    },
    fulfillment: "pickup",
    address: null,
    price: {
      printing: 50,
      binding: 30,
      services: 0,
      delivery: 0,
      discount: 0,
      total: 80,
      billablePages: 28,
    },
    paymentMethod: "full",
    amountPaid: 80,
    balance: 0,
    paymentStatus: "paid",
    status: "COMPLETED",
    createdAt: ago(60 * 26),
    updatedAt: ago(60 * 25),
    timeline: [
      { status: "NEW", at: ago(60 * 26) },
      { status: "ACCEPTED", at: ago(60 * 26 - 5) },
      { status: "PRINTING", at: ago(60 * 26 - 20) },
      { status: "FINISHING", at: ago(60 * 25 - 40) },
      { status: "READY_PICKUP", at: ago(60 * 25 - 20) },
      { status: "COMPLETED", at: ago(60 * 25) },
    ],
  },
];
