import type {
  Address,
  CustomerProfile,
  Order,
  Shop,
  Review,
  Notification,
  SupportTicket,
  ShopApplication,
  ShopkeeperProfile,
  PaperType,
} from "@/types";

const NOW = new Date("2026-09-20T08:00:00.000Z").getTime();

export function ago(mins: number): string {
  return new Date(NOW - mins * 60000).toISOString();
}

export function daysAgo(days: number): string {
  return new Date(NOW - days * 86400000).toISOString();
}

function paper(
  id: string,
  name: string,
  enabled: boolean,
  bwPrice: number,
  colorPrice: number,
  colorEnabled = true,
): PaperType {
  return {
    id,
    name,
    enabled,
    bwEnabled: true,
    bwPrice,
    colorEnabled,
    colorPrice,
    single: true,
    double: true,
  };
}

export const demoProfile: CustomerProfile = {
  name: "Tamil Kumaran",
  email: "tamil.kumaran@gmail.com",
  phone: "+91 98765 43210",
  alternatephone: "+91 87654 32109",
  addressLine1: "4B, Kamaraj Nagar 2nd Street",
  addressLine2: "Near FACT Colony",
  city: "Coimbatore",
  state: "Tamil Nadu",
  zip: "641004",
  country: "India",
  payoutMethod: "upi",
  upiId: "tamilkumaran@upi",
  upiVerified: true,
};

export const demoAddresses: Address[] = [
  {
    id: "addr-home",
    label: "Home",
    name: "Tamil Kumaran",
    phone: "+91 98765 43210",
    house: "4B",
    street: "Kamaraj Nagar 2nd Street",
    area: "Peelamedu",
    city: "Coimbatore",
    pincode: "641004",
  },
  {
    id: "addr-college",
    label: "College",
    name: "Tamil Kumaran",
    phone: "+91 98765 43210",
    house: "PSG College of Technology",
    street: "College Road",
    area: "Peelamedu",
    city: "Coimbatore",
    pincode: "641004",
  },
  {
    id: "addr-office",
    label: "Office",
    name: "Tamil Kumaran",
    phone: "+91 98765 43210",
    house: "3rd Floor, Tidel Park",
    street: "Nehru Nagar",
    area: "Gandhipuram",
    city: "Coimbatore",
    pincode: "641012",
  },
];

export const demoShops: Shop[] = [
  {
    id: "shop-tamil-printers",
    name: "Tamil Printers",
    ownerName: "Ramesh Kumar",
    ownerPhone: "+91 98431 22100",
    phone: "+91 98431 22110",
    email: "tamilprinters@ordermyxerox.in",
    address: "12, Gandhi Street, Gandhipuram, Coimbatore - 641012",
    addressLine1: "12, Gandhi Street",
    addressLine2: "Near Gandhipuram Bus Stand",
    city: "Coimbatore",
    state: "Tamil Nadu",
    zip: "641012",
    country: "India",
    hours: "Mon - Sat, 8:00 AM - 9:00 PM",
    workingDaysFrom: "Mon",
    workingDaysTo: "Sat",
    openingTime: "08:00",
    closingTime: "21:00",
    rating: 4.8,
    distanceKm: 1.2,
    prepMinutes: 20,
    pickup: true,
    paperTypes: [
      paper("a4", "A4 Paper", true, 2, 10),
      paper("a3", "A3 Paper", true, 4, 18),
      paper("a5", "A5 Paper", true, 1.5, 8),
      paper("bond", "Bond Sheet", true, 3, 12),
      paper("photo-4", "Photo-4 (4x6)", true, 15, 30),
      paper("photo-8", "Photo-8 (8x10)", true, 25, 50),
    ],
    printTypes: { bw: true, color: true },
    printSides: { single: true, double: true },
    orientation: { portrait: true, landscape: true },
    binding: [
      { id: "spiral", name: "Spiral Binding", enabled: true, price: 40 },
      { id: "soft", name: "Soft Binding", enabled: true, price: 70 },
      { id: "hard", name: "Hard Binding", enabled: false, price: 180 },
    ],
    additional: [
      { id: "lamination", name: "Lamination", enabled: true, price: 10, perPage: true },
      { id: "stapling", name: "Stapling", enabled: true, price: 5 },
    ],
    delivery: {
      enabled: true,
      fee: 30,
      freeAbove: 500,
      etaMinutes: "30-45 minutes",
      areas: ["Gandhipuram", "R.S. Puram", "Peelamedu", "Saibaba Colony"],
    },
    payments: {
      full: true,
      advance: true,
      cashPickup: true,
      cashDelivery: true,
      advancePercent: 30,
    },
    accountStatus: "active",
    ownerAccountId: "acc-shop-1",
    isOpen: true,
    shopPaymentMethod: "upi",
    upiId: "rameshkumar@bankupi",
    upiVerified: true,
    frontImage: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgZmlsbD0iI2YwZjBmMCIvPjx0ZXh0IHg9IjEwMCIgeT0iNzUiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM5OTkiIGZvbnQtc2l6ZT0iMTQiPlNob3AgRnJvbnQ8L3RleHQ+PC9zdmc+",
    interiorImage: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgZmlsbD0iI2YwZjBmMCIvPjx0ZXh0IHg9IjEwMCIgeT0iNzUiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM5OTkiIGZvbnQtc2l6ZT0iMTQiPlNob3AgSW50ZXJpb3I8L3RleHQ+PC9zdmc+",
  },
  {
    id: "shop-annai-prints",
    name: "Annai Prints & Stationery",
    ownerName: "Lakshmi Narayanan",
    ownerPhone: "+91 99406 78110",
    phone: "+91 99406 78120",
    email: "annaiprints@ordermyxerox.in",
    address: "7A, Cross Cut Road, Coimbatore - 641045",
    addressLine1: "7A, Cross Cut Road",
    addressLine2: "Opposite CSI Church",
    city: "Coimbatore",
    state: "Tamil Nadu",
    zip: "641045",
    country: "India",
    hours: "Mon - Sun, 9:00 AM - 10:00 PM",
    workingDaysFrom: "Mon",
    workingDaysTo: "Sun",
    openingTime: "09:00",
    closingTime: "22:00",
    rating: 4.6,
    distanceKm: 2.4,
    prepMinutes: 30,
    pickup: true,
    paperTypes: [
      paper("a4", "A4 Paper", true, 1.5, 9),
      paper("a3", "A3 Paper", false, 4, 18),
      paper("a5", "A5 Paper", true, 1.2, 7),
      paper("bond", "Bond Sheet", true, 2.5, 11),
      paper("photo-4", "Photo-4 (4x6)", true, 14, 28),
      paper("photo-8", "Photo-8 (8x10)", true, 24, 48),
    ],
    printTypes: { bw: true, color: true },
    printSides: { single: true, double: false },
    orientation: { portrait: true, landscape: false },
    binding: [
      { id: "spiral", name: "Spiral Binding", enabled: true, price: 35 },
      { id: "soft", name: "Soft Binding", enabled: false, price: 70 },
      { id: "hard", name: "Hard Binding", enabled: true, price: 160 },
    ],
    additional: [
      { id: "lamination", name: "Lamination", enabled: true, price: 12, perPage: true },
      { id: "stapling", name: "Stapling", enabled: false, price: 5 },
    ],
    delivery: {
      enabled: false,
      fee: 25,
      freeAbove: null,
      etaMinutes: "45-60 minutes",
      areas: [],
    },
    payments: {
      full: true,
      advance: true,
      cashPickup: true,
      cashDelivery: false,
      advancePercent: 30,
    },
    accountStatus: "active",
    ownerAccountId: "acc-shop-2",
    isOpen: true,
    shopPaymentMethod: "upi",
    upiId: "lakshminarayanan@upi",
    upiVerified: true,
    frontImage: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgZmlsbD0iI2YwZjBmMCIvPjx0ZXh0IHg9IjEwMCIgeT0iNzUiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM5OTkiIGZvbnQtc2l6ZT0iMTQiPlNob3AgRnJvbnQ8L3RleHQ+PC9zdmc+",
    interiorImage: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgZmlsbD0iI2YwZjBmMCIvPjx0ZXh0IHg9IjEwMCIgeT0iNzUiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM5OTkiIGZvbnQtc2l6ZT0iMTQiPlNob3AgSW50ZXJpb3I8L3RleHQ+PC9zdmc+",
  },
  {
    id: "shop-campus-copy",
    name: "Campus Copy Centre",
    ownerName: "Arun Prasad",
    ownerPhone: "+91 90035 41266",
    phone: "+91 90035 41267",
    email: "campuscopy@ordermyxerox.in",
    address: "Opp. PSG College Gate, Peelamedu, Coimbatore - 641004",
    addressLine1: "Opp. PSG College of Technology",
    addressLine2: "Main Gate, Peelamedu",
    city: "Coimbatore",
    state: "Tamil Nadu",
    zip: "641004",
    country: "India",
    hours: "Mon - Sat, 7:30 AM - 8:30 PM",
    workingDaysFrom: "Mon",
    workingDaysTo: "Sat",
    openingTime: "07:30",
    closingTime: "20:30",
    rating: 4.9,
    distanceKm: 3.1,
    prepMinutes: 15,
    pickup: true,
    paperTypes: [
      paper("a4", "A4 Paper", true, 1.8, 8),
      paper("a3", "A3 Paper", true, 3.5, 16),
      paper("a5", "A5 Paper", true, 1.3, 6),
      paper("bond", "Bond Sheet", false, 3, 12),
      paper("photo-4", "Photo-4 (4x6)", false, 15, 30),
      paper("photo-8", "Photo-8 (8x10)", false, 25, 50),
    ],
    printTypes: { bw: true, color: true },
    printSides: { single: true, double: true },
    orientation: { portrait: true, landscape: true },
    binding: [
      { id: "spiral", name: "Spiral Binding", enabled: true, price: 30 },
      { id: "soft", name: "Soft Binding", enabled: true, price: 60 },
      { id: "hard", name: "Hard Binding", enabled: false, price: 180 },
    ],
    additional: [
      { id: "lamination", name: "Lamination", enabled: false, price: 10, perPage: true },
      { id: "stapling", name: "Stapling", enabled: true, price: 4 },
    ],
    delivery: {
      enabled: true,
      fee: 20,
      freeAbove: 400,
      etaMinutes: "25-40 minutes",
      areas: ["Peelamedu", "Hope College", "Singanallur"],
    },
    payments: {
      full: true,
      advance: false,
      cashPickup: true,
      cashDelivery: true,
      advancePercent: 25,
    },
    accountStatus: "active",
    ownerAccountId: "acc-shop-3",
    isOpen: true,
    shopPaymentMethod: "upi",
    upiId: "arunprasad@upi",
    upiVerified: true,
    frontImage: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgZmlsbD0iI2YwZjBmMCIvPjx0ZXh0IHg9IjEwMCIgeT0iNzUiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM5OTkiIGZvbnQtc2l6ZT0iMTQiPlNob3AgRnJvbnQ8L3RleHQ+PC9zdmc+",
    interiorImage: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgZmlsbD0iI2YwZjBmMCIvPjx0ZXh0IHg9IjEwMCIgeT0iNzUiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM5OTkiIGZvbnQtc2l6ZT0iMTQiPlNob3AgSW50ZXJpb3I8L3RleHQ+PC9zdmc+",
  },
  {
    id: "shop-sri-lakshmi",
    name: "Sri Lakshmi Xerox",
    ownerName: "Lakshmi Devi",
    ownerPhone: "+91 98765 11110",
    phone: "+91 98765 11111",
    email: "srilakshmi@ordermyxerox.in",
    address: "Avinashi Road, Peelamedu, Coimbatore - 641004",
    addressLine1: "45, Avinashi Road",
    addressLine2: "Near CMCH Hospital",
    city: "Coimbatore",
    state: "Tamil Nadu",
    zip: "641004",
    country: "India",
    hours: "Mon - Sat, 8:30 AM - 8:30 PM",
    workingDaysFrom: "Mon",
    workingDaysTo: "Sat",
    openingTime: "08:30",
    closingTime: "20:30",
    rating: 4.7,
    distanceKm: 2.0,
    prepMinutes: 20,
    pickup: true,
    paperTypes: [
      paper("a4", "A4 Paper", true, 1.7, 9),
      paper("a3", "A3 Paper", true, 3.5, 16),
      paper("a5", "A5 Paper", true, 1.2, 7),
      paper("bond", "Bond Sheet", true, 2.5, 11),
      paper("photo-4", "Photo-4 (4x6)", true, 14, 28),
      paper("photo-8", "Photo-8 (8x10)", true, 23, 46),
    ],
    printTypes: { bw: true, color: true },
    printSides: { single: true, double: true },
    orientation: { portrait: true, landscape: true },
    binding: [
      { id: "spiral", name: "Spiral Binding", enabled: true, price: 38 },
      { id: "soft", name: "Soft Binding", enabled: true, price: 68 },
      { id: "hard", name: "Hard Binding", enabled: false, price: 175 },
    ],
    additional: [
      { id: "lamination", name: "Lamination", enabled: true, price: 10, perPage: true },
      { id: "stapling", name: "Stapling", enabled: true, price: 4 },
    ],
    delivery: {
      enabled: true,
      fee: 25,
      freeAbove: 400,
      etaMinutes: "25-40 minutes",
      areas: ["Peelamedu", "Gandhipuram", "Saibaba Colony"],
    },
    payments: {
      full: true,
      advance: true,
      cashPickup: true,
      cashDelivery: true,
      advancePercent: 30,
    },
    accountStatus: "active",
    ownerAccountId: "acc-shop-4",
    isOpen: false,
    shopPaymentMethod: "upi",
    upiId: "lakshmidevi@upi",
    upiVerified: true,
    frontImage: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgZmlsbD0iI2YwZjBmMCIvPjx0ZXh0IHg9IjEwMCIgeT0iNzUiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM5OTkiIGZvbnQtc2l6ZT0iMTQiPlNob3AgRnJvbnQ8L3RleHQ+PC9zdmc+",
    interiorImage: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgZmlsbD0iI2YwZjBmMCIvPjx0ZXh0IHg9IjEwMCIgeT0iNzUiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM5OTkiIGZvbnQtc2l6ZT0iMTQiPlNob3AgSW50ZXJpb3I8L3RleHQ+PC9zdmc+",
  },
  {
    id: "shop-city-copy",
    name: "City Copy Point",
    ownerName: "Rajesh Kumar",
    ownerPhone: "+91 99876 22221",
    phone: "+91 99876 22222",
    email: "citycopy@ordermyxerox.in",
    address: "RS Puram, Coimbatore - 641002",
    addressLine1: "23, DB Road",
    addressLine2: "Near RS Puram Police Station",
    city: "Coimbatore",
    state: "Tamil Nadu",
    zip: "641002",
    country: "India",
    hours: "Mon - Sun, 8:00 AM - 9:30 PM",
    workingDaysFrom: "Mon",
    workingDaysTo: "Sun",
    openingTime: "08:00",
    closingTime: "21:30",
    rating: 4.5,
    distanceKm: 3.2,
    prepMinutes: 25,
    pickup: true,
    paperTypes: [
      paper("a4", "A4 Paper", true, 1.5, 8),
      paper("a3", "A3 Paper", true, 3, 14),
      paper("a5", "A5 Paper", true, 1, 6),
      paper("bond", "Bond Sheet", true, 2, 10),
      paper("photo-4", "Photo-4 (4x6)", true, 13, 26),
      paper("photo-8", "Photo-8 (8x10)", true, 22, 44),
    ],
    printTypes: { bw: true, color: true },
    printSides: { single: true, double: false },
    orientation: { portrait: true, landscape: false },
    binding: [
      { id: "spiral", name: "Spiral Binding", enabled: true, price: 32 },
      { id: "soft", name: "Soft Binding", enabled: false, price: 60 },
      { id: "hard", name: "Hard Binding", enabled: true, price: 165 },
    ],
    additional: [
      { id: "lamination", name: "Lamination", enabled: true, price: 9, perPage: true },
      { id: "stapling", name: "Stapling", enabled: true, price: 3 },
    ],
    delivery: {
      enabled: false,
      fee: 20,
      freeAbove: null,
      etaMinutes: "30-45 minutes",
      areas: [],
    },
    payments: {
      full: true,
      advance: false,
      cashPickup: true,
      cashDelivery: false,
      advancePercent: 25,
    },
    accountStatus: "active",
    ownerAccountId: "acc-shop-5",
    isOpen: true,
    shopPaymentMethod: "upi",
    upiId: "rajeshkumar@upi",
    upiVerified: true,
    frontImage: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgZmlsbD0iI2YwZjBmMCIvPjx0ZXh0IHg9IjEwMCIgeT0iNzUiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM5OTkiIGZvbnQtc2l6ZT0iMTQiPlNob3AgRnJvbnQ8L3RleHQ+PC9zdmc+",
    interiorImage: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgZmlsbD0iI2YwZjBmMCIvPjx0ZXh0IHg9IjEwMCIgeT0iNzUiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM5OTkiIGZvbnQtc2l6ZT0iMTQiPlNob3AgSW50ZXJpb3I8L3RleHQ+PC9zdmc+",
  },
  {
    id: "shop-psg-print",
    name: "PSG Print Hub",
    ownerName: "Anand Prasad",
    ownerPhone: "+91 97654 33332",
    phone: "+91 97654 33333",
    email: "psgprint@ordermyxerox.in",
    address: "Peelamedu, Coimbatore - 641004",
    addressLine1: "8, PSN Layout",
    addressLine2: "Near PSG Tech Main Building",
    city: "Coimbatore",
    state: "Tamil Nadu",
    zip: "641004",
    country: "India",
    hours: "Mon - Sat, 9:00 AM - 8:00 PM",
    workingDaysFrom: "Mon",
    workingDaysTo: "Sat",
    openingTime: "09:00",
    closingTime: "20:00",
    rating: 4.8,
    distanceKm: 2.6,
    prepMinutes: 15,
    pickup: true,
    paperTypes: [
      paper("a4", "A4 Paper", true, 1.6, 8),
      paper("a3", "A3 Paper", true, 3.2, 15),
      paper("a5", "A5 Paper", true, 1.1, 6),
      paper("bond", "Bond Sheet", true, 2.2, 10),
      paper("photo-4", "Photo-4 (4x6)", false, 14, 28),
      paper("photo-8", "Photo-8 (8x10)", false, 24, 48),
    ],
    printTypes: { bw: true, color: true },
    printSides: { single: true, double: true },
    orientation: { portrait: true, landscape: true },
    binding: [
      { id: "spiral", name: "Spiral Binding", enabled: true, price: 35 },
      { id: "soft", name: "Soft Binding", enabled: true, price: 65 },
      { id: "hard", name: "Hard Binding", enabled: false, price: 180 },
    ],
    additional: [
      { id: "lamination", name: "Lamination", enabled: true, price: 10, perPage: true },
      { id: "stapling", name: "Stapling", enabled: true, price: 5 },
    ],
    delivery: {
      enabled: true,
      fee: 20,
      freeAbove: 350,
      etaMinutes: "20-35 minutes",
      areas: ["Peelamedu", "Hope College", "Gandhipuram"],
    },
    payments: {
      full: true,
      advance: true,
      cashPickup: true,
      cashDelivery: true,
      advancePercent: 25,
    },
    accountStatus: "active",
    ownerAccountId: "acc-shop-6",
    isOpen: false,
    shopPaymentMethod: "upi",
    upiId: "anandprasad@upi",
    upiVerified: true,
    frontImage: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgZmlsbD0iI2YwZjBmMCIvPjx0ZXh0IHg9IjEwMCIgeT0iNzUiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM5OTkiIGZvbnQtc2l6ZT0iMTQiPlNob3AgRnJvbnQ8L3RleHQ+PC9zdmc+",
    interiorImage: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgZmlsbD0iI2YwZjBmMCIvPjx0ZXh0IHg9IjEwMCIgeT0iNzUiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM5OTkiIGZvbnQtc2l6ZT0iMTQiPlNob3AgSW50ZXJpb3I8L3RleHQ+PC9zdmc+",
  },
  {
    id: "shop-kumar-xerox",
    name: "Kumar Xerox & Stationery",
    ownerName: "Kumaravel",
    ownerPhone: "+91 96543 44443",
    phone: "+91 96543 44444",
    email: "kumarxerox@ordermyxerox.in",
    address: "Gandhipuram, Coimbatore - 641012",
    addressLine1: "56, Mettupalayam Road",
    addressLine2: "Near Gandhipuram Town Hall",
    city: "Coimbatore",
    state: "Tamil Nadu",
    zip: "641012",
    country: "India",
    hours: "Mon - Sat, 8:00 AM - 9:00 PM",
    workingDaysFrom: "Mon",
    workingDaysTo: "Sat",
    openingTime: "08:00",
    closingTime: "21:00",
    rating: 4.6,
    distanceKm: 1.5,
    prepMinutes: 20,
    pickup: true,
    paperTypes: [
      paper("a4", "A4 Paper", true, 1.8, 9),
      paper("a3", "A3 Paper", true, 3.5, 16),
      paper("a5", "A5 Paper", true, 1.3, 7),
      paper("bond", "Bond Sheet", true, 2.5, 11),
      paper("photo-4", "Photo-4 (4x6)", true, 15, 30),
      paper("photo-8", "Photo-8 (8x10)", true, 25, 50),
    ],
    printTypes: { bw: true, color: true },
    printSides: { single: true, double: true },
    orientation: { portrait: true, landscape: false },
    binding: [
      { id: "spiral", name: "Spiral Binding", enabled: true, price: 40 },
      { id: "soft", name: "Soft Binding", enabled: true, price: 70 },
      { id: "hard", name: "Hard Binding", enabled: false, price: 185 },
    ],
    additional: [
      { id: "lamination", name: "Lamination", enabled: true, price: 11, perPage: true },
      { id: "stapling", name: "Stapling", enabled: true, price: 5 },
    ],
    delivery: {
      enabled: false,
      fee: 25,
      freeAbove: null,
      etaMinutes: "25-40 minutes",
      areas: [],
    },
    payments: {
      full: true,
      advance: true,
      cashPickup: true,
      cashDelivery: false,
      advancePercent: 30,
    },
    accountStatus: "active",
    ownerAccountId: "acc-shop-7",
    isOpen: true,
    shopPaymentMethod: "upi",
    upiId: "kumaravel@upi",
    upiVerified: true,
    frontImage: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgZmlsbD0iI2YwZjBmMCIvPjx0ZXh0IHg9IjEwMCIgeT0iNzUiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM5OTkiIGZvbnQtc2l6ZT0iMTQiPlNob3AgRnJvbnQ8L3RleHQ+PC9zdmc+",
    interiorImage: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgZmlsbD0iI2YwZjBmMCIvPjx0ZXh0IHg9IjEwMCIgeT0iNzUiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM5OTkiIGZvbnQtc2l6ZT0iMTQiPlNob3AgSW50ZXJpb3I8L3RleHQ+PC9zdmc+",
  },
  {
    id: "shop-smart-print",
    name: "Smart Print Centre",
    ownerName: "Senthil Murugan",
    ownerPhone: "+91 95432 55554",
    phone: "+91 95432 55555",
    email: "smartprint@ordermyxerox.in",
    address: "Saibaba Colony, Coimbatore - 641011",
    addressLine1: "12, Sathy Road",
    addressLine2: "Near Saibaba Temple",
    city: "Coimbatore",
    state: "Tamil Nadu",
    zip: "641011",
    country: "India",
    hours: "Mon - Sun, 9:00 AM - 9:00 PM",
    workingDaysFrom: "Mon",
    workingDaysTo: "Sun",
    openingTime: "09:00",
    closingTime: "21:00",
    rating: 4.7,
    distanceKm: 4.0,
    prepMinutes: 20,
    pickup: true,
    paperTypes: [
      paper("a4", "A4 Paper", true, 1.5, 7),
      paper("a3", "A3 Paper", true, 3, 14),
      paper("a5", "A5 Paper", true, 1, 5),
      paper("bond", "Bond Sheet", true, 2, 9),
      paper("photo-4", "Photo-4 (4x6)", true, 13, 26),
      paper("photo-8", "Photo-8 (8x10)", true, 22, 44),
    ],
    printTypes: { bw: true, color: true },
    printSides: { single: true, double: true },
    orientation: { portrait: true, landscape: true },
    binding: [
      { id: "spiral", name: "Spiral Binding", enabled: true, price: 33 },
      { id: "soft", name: "Soft Binding", enabled: true, price: 60 },
      { id: "hard", name: "Hard Binding", enabled: true, price: 170 },
    ],
    additional: [
      { id: "lamination", name: "Lamination", enabled: true, price: 8, perPage: true },
      { id: "stapling", name: "Stapling", enabled: true, price: 3 },
    ],
    delivery: {
      enabled: true,
      fee: 30,
      freeAbove: 450,
      etaMinutes: "30-45 minutes",
      areas: ["Saibaba Colony", "Peelamedu", "R.S. Puram"],
    },
    payments: {
      full: true,
      advance: true,
      cashPickup: true,
      cashDelivery: true,
      advancePercent: 20,
    },
    accountStatus: "active",
    ownerAccountId: "acc-shop-8",
    isOpen: true,
    shopPaymentMethod: "upi",
    upiId: "senthilmurugan@upi",
    upiVerified: true,
    frontImage: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgZmlsbD0iI2YwZjBmMCIvPjx0ZXh0IHg9IjEwMCIgeT0iNzUiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM5OTkiIGZvbnQtc2l6ZT0iMTQiPlNob3AgRnJvbnQ8L3RleHQ+PC9zdmc+",
    interiorImage: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjE1MCIgZmlsbD0iI2YwZjBmMCIvPjx0ZXh0IHg9IjEwMCIgeT0iNzUiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM5OTkiIGZvbnQtc2l6ZT0iMTQiPlNob3AgSW50ZXJpb3I8L3RleHQ+PC9zdmc+",
  },
];

export const demoOrders: Order[] = [
  {
    id: "OMX-1001",
    customerName: "Tamil Kumaran",
    customerPhone: "+91 98765 43210",
    shopId: "shop-tamil-printers",
    shopName: "Tamil Printers",
    documents: [
      { id: "doc-001", name: "Assignment.pdf", pages: 15, sizeMb: 2.4 },
    ],
    config: {
      paperTypeId: "a4",
      printType: "bw",
      side: "double",
      copies: 2,
      pageRangeMode: "all",
      pageRange: "",
      orientation: "portrait",
      bindingId: "spiral",
      additionalIds: [],
    },
    configLabels: {
      paper: "A4 Paper",
      printType: "Black & White",
      side: "Double Side",
      orientation: "Portrait",
      binding: "Spiral Binding",
      additional: [],
    },
    fulfillment: "pickup",
    address: null,
    price: {
      printing: 54,
      binding: 80,
      services: 0,
      delivery: 0,
      discount: 0,
      total: 134,
      billablePages: 30,
    },
    paymentMethod: "full",
    amountPaid: 134,
    balance: 0,
    paymentStatus: "paid",
    status: "NEW",
    createdAt: ago(12),
    updatedAt: ago(12),
    timeline: [{ status: "NEW", at: ago(12) }],
  },
  {
    id: "OMX-1002",
    customerName: "Tamil Kumaran",
    customerPhone: "+91 98765 43210",
    shopId: "shop-campus-copy",
    shopName: "Campus Copy Centre",
    documents: [
      { id: "doc-002", name: "Project-Report.pdf", pages: 42, sizeMb: 6.1 },
    ],
    config: {
      paperTypeId: "a4",
      printType: "color",
      side: "single",
      copies: 1,
      pageRangeMode: "all",
      pageRange: "",
      orientation: "portrait",
      bindingId: "soft",
      additionalIds: ["lamination"],
    },
    configLabels: {
      paper: "A4 Paper",
      printType: "Colour",
      side: "Single Side",
      orientation: "Portrait",
      binding: "Soft Binding",
      additional: ["Lamination"],
    },
    fulfillment: "pickup",
    address: null,
    price: {
      printing: 336,
      binding: 60,
      services: 420,
      delivery: 0,
      discount: 0,
      total: 816,
      billablePages: 42,
    },
    paymentMethod: "full",
    amountPaid: 816,
    balance: 0,
    paymentStatus: "paid",
    status: "ACCEPTED",
    createdAt: ago(90),
    updatedAt: ago(75),
    timeline: [
      { status: "NEW", at: ago(90) },
      { status: "ACCEPTED", at: ago(75) },
    ],
  },
  {
    id: "OMX-1003",
    customerName: "Tamil Kumaran",
    customerPhone: "+91 98765 43210",
    shopId: "shop-annai-prints",
    shopName: "Annai Prints & Stationery",
    documents: [
      { id: "doc-003", name: "ID-Proof.pdf", pages: 2, sizeMb: 0.4 },
    ],
    config: {
      paperTypeId: "a4",
      printType: "bw",
      side: "single",
      copies: 3,
      pageRangeMode: "all",
      pageRange: "",
      orientation: "portrait",
      bindingId: null,
      additionalIds: ["stapling"],
    },
    configLabels: {
      paper: "A4 Paper",
      printType: "Black & White",
      side: "Single Side",
      orientation: "Portrait",
      binding: "None",
      additional: ["Stapling"],
    },
    fulfillment: "pickup",
    address: null,
    price: {
      printing: 12,
      binding: 0,
      services: 15,
      delivery: 0,
      discount: 0,
      total: 27,
      billablePages: 6,
    },
    paymentMethod: "cash_pickup",
    amountPaid: 0,
    balance: 27,
    paymentStatus: "unpaid",
    status: "PRINTING",
    createdAt: ago(180),
    updatedAt: ago(120),
    timeline: [
      { status: "NEW", at: ago(180) },
      { status: "ACCEPTED", at: ago(165) },
      { status: "PRINTING", at: ago(120) },
    ],
  },
  {
    id: "OMX-1004",
    customerName: "Tamil Kumaran",
    customerPhone: "+91 98765 43210",
    shopId: "shop-sri-lakshmi",
    shopName: "Sri Lakshmi Xerox",
    documents: [
      { id: "doc-004", name: "Lab-Record.pdf", pages: 28, sizeMb: 3.2 },
    ],
    config: {
      paperTypeId: "a4",
      printType: "bw",
      side: "single",
      copies: 1,
      pageRangeMode: "all",
      pageRange: "",
      orientation: "portrait",
      bindingId: "spiral",
      additionalIds: [],
    },
    configLabels: {
      paper: "A4 Paper",
      printType: "Black & White",
      side: "Single Side",
      orientation: "Portrait",
      binding: "Spiral Binding",
      additional: [],
    },
    fulfillment: "pickup",
    address: null,
    price: {
      printing: 50,
      binding: 30,
      services: 0,
      delivery: 0,
      discount: 0,
      total: 80,
      billablePages: 28,
    },
    paymentMethod: "full",
    amountPaid: 80,
    balance: 0,
    paymentStatus: "paid",
    status: "FINISHING",
    createdAt: ago(300),
    updatedAt: ago(150),
    timeline: [
      { status: "NEW", at: ago(300) },
      { status: "ACCEPTED", at: ago(280) },
      { status: "PRINTING", at: ago(220) },
      { status: "FINISHING", at: ago(150) },
    ],
  },
  {
    id: "OMX-1005",
    customerName: "Tamil Kumaran",
    customerPhone: "+91 98765 43210",
    shopId: "shop-tamil-printers",
    shopName: "Tamil Printers",
    documents: [
      { id: "doc-005", name: "Thesis-Chapter1.pdf", pages: 65, sizeMb: 8.7 },
    ],
    config: {
      paperTypeId: "a4",
      printType: "bw",
      side: "double",
      copies: 1,
      pageRangeMode: "all",
      pageRange: "",
      orientation: "portrait",
      bindingId: "hard",
      additionalIds: [],
    },
    configLabels: {
      paper: "A4 Paper",
      printType: "Black & White",
      side: "Double Side",
      orientation: "Portrait",
      binding: "Hard Binding",
      additional: [],
    },
    fulfillment: "pickup",
    address: null,
    price: {
      printing: 234,
      binding: 180,
      services: 0,
      delivery: 0,
      discount: 0,
      total: 414,
      billablePages: 130,
    },
    paymentMethod: "full",
    amountPaid: 414,
    balance: 0,
    paymentStatus: "paid",
    status: "READY_PICKUP",
    createdAt: ago(500),
    updatedAt: ago(60),
    timeline: [
      { status: "NEW", at: ago(500) },
      { status: "ACCEPTED", at: ago(480) },
      { status: "PRINTING", at: ago(400) },
      { status: "FINISHING", at: ago(200) },
      { status: "READY_PICKUP", at: ago(60) },
    ],
  },
  {
    id: "OMX-1006",
    customerName: "Tamil Kumaran",
    customerPhone: "+91 98765 43210",
    shopId: "shop-psg-print",
    shopName: "PSG Print Hub",
    documents: [
      { id: "doc-006", name: "Resume.pdf", pages: 2, sizeMb: 0.3 },
      { id: "doc-007", name: "Presentation.pdf", pages: 18, sizeMb: 4.5 },
    ],
    config: {
      paperTypeId: "a4",
      printType: "color",
      side: "single",
      copies: 2,
      pageRangeMode: "all",
      pageRange: "",
      orientation: "portrait",
      bindingId: "spiral",
      additionalIds: ["lamination"],
    },
    configLabels: {
      paper: "A4 Paper",
      printType: "Colour",
      side: "Single Side",
      orientation: "Portrait",
      binding: "Spiral Binding",
      additional: ["Lamination"],
    },
    fulfillment: "delivery",
    address: demoAddresses[1],
    price: {
      printing: 720,
      binding: 60,
      services: 400,
      delivery: 20,
      discount: 0,
      total: 1200,
      billablePages: 40,
    },
    paymentMethod: "advance",
    amountPaid: 360,
    balance: 840,
    paymentStatus: "partial",
    status: "READY_DELIVERY",
    createdAt: ago(400),
    updatedAt: ago(80),
    timeline: [
      { status: "NEW", at: ago(400) },
      { status: "ACCEPTED", at: ago(380) },
      { status: "PRINTING", at: ago(320) },
      { status: "FINISHING", at: ago(180) },
      { status: "READY_DELIVERY", at: ago(80) },
    ],
  },
  {
    id: "OMX-1007",
    customerName: "Tamil Kumaran",
    customerPhone: "+91 98765 43210",
    shopId: "shop-tamil-printers",
    shopName: "Tamil Printers",
    documents: [
      { id: "doc-008", name: "Notes-Ch5.pdf", pages: 12, sizeMb: 1.8 },
    ],
    config: {
      paperTypeId: "a4",
      printType: "bw",
      side: "double",
      copies: 1,
      pageRangeMode: "all",
      pageRange: "",
      orientation: "portrait",
      bindingId: "spiral",
      additionalIds: [],
    },
    configLabels: {
      paper: "A4 Paper",
      printType: "Black & White",
      side: "Double Side",
      orientation: "Portrait",
      binding: "Spiral Binding",
      additional: [],
    },
    fulfillment: "delivery",
    address: demoAddresses[0],
    price: {
      printing: 24,
      binding: 40,
      services: 0,
      delivery: 30,
      discount: 0,
      total: 94,
      billablePages: 12,
    },
    paymentMethod: "full",
    amountPaid: 94,
    balance: 0,
    paymentStatus: "paid",
    status: "OUT_FOR_DELIVERY",
    createdAt: ago(240),
    updatedAt: ago(20),
    timeline: [
      { status: "NEW", at: ago(240) },
      { status: "ACCEPTED", at: ago(225) },
      { status: "PRINTING", at: ago(190) },
      { status: "FINISHING", at: ago(120) },
      { status: "READY_DELIVERY", at: ago(50) },
      { status: "OUT_FOR_DELIVERY", at: ago(20) },
    ],
  },
  {
    id: "OMX-1008",
    customerName: "Tamil Kumaran",
    customerPhone: "+91 98765 43210",
    shopId: "shop-smart-print",
    shopName: "Smart Print Centre",
    documents: [
      { id: "doc-009", name: "Invoice-March.pdf", pages: 3, sizeMb: 0.5 },
    ],
    config: {
      paperTypeId: "a4",
      printType: "bw",
      side: "single",
      copies: 1,
      pageRangeMode: "all",
      pageRange: "",
      orientation: "portrait",
      bindingId: null,
      additionalIds: ["stapling"],
    },
    configLabels: {
      paper: "A4 Paper",
      printType: "Black & White",
      side: "Single Side",
      orientation: "Portrait",
      binding: "None",
      additional: ["Stapling"],
    },
    fulfillment: "delivery",
    address: demoAddresses[2],
    price: {
      printing: 3,
      binding: 0,
      services: 4,
      delivery: 20,
      discount: 0,
      total: 27,
      billablePages: 3,
    },
    paymentMethod: "full",
    amountPaid: 27,
    balance: 0,
    paymentStatus: "paid",
    status: "DELIVERED",
    createdAt: ago(1440),
    updatedAt: ago(1000),
    timeline: [
      { status: "NEW", at: ago(1440) },
      { status: "ACCEPTED", at: ago(1420) },
      { status: "PRINTING", at: ago(1380) },
      { status: "FINISHING", at: ago(1200) },
      { status: "READY_DELIVERY", at: ago(1100) },
      { status: "OUT_FOR_DELIVERY", at: ago(1050) },
      { status: "DELIVERED", at: ago(1000) },
    ],
  },
  {
    id: "OMX-1009",
    customerName: "Tamil Kumaran",
    customerPhone: "+91 98765 43210",
    shopId: "shop-tamil-printers",
    shopName: "Tamil Printers",
    documents: [
      { id: "doc-010", name: "Photos-Collection.pdf", pages: 8, sizeMb: 5.2 },
    ],
    config: {
      paperTypeId: "photo-4",
      printType: "color",
      side: "single",
      copies: 2,
      pageRangeMode: "all",
      pageRange: "",
      orientation: "portrait",
      bindingId: null,
      additionalIds: [],
    },
    configLabels: {
      paper: "Photo-4 (4x6)",
      printType: "Colour",
      side: "Single Side",
      orientation: "Portrait",
      binding: "None",
      additional: [],
    },
    fulfillment: "pickup",
    address: null,
    price: {
      printing: 480,
      binding: 0,
      services: 0,
      delivery: 0,
      discount: 0,
      total: 480,
      billablePages: 16,
    },
    paymentMethod: "full",
    amountPaid: 480,
    balance: 0,
    paymentStatus: "paid",
    status: "COMPLETED",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
    timeline: [
      { status: "NEW", at: daysAgo(3) },
      { status: "ACCEPTED", at: daysAgo(3) },
      { status: "PRINTING", at: daysAgo(3) },
      { status: "FINISHING", at: daysAgo(3) },
      { status: "READY_PICKUP", at: daysAgo(3) },
      { status: "COMPLETED", at: daysAgo(3) },
    ],
  },
  {
    id: "OMX-1010",
    customerName: "Tamil Kumaran",
    customerPhone: "+91 98765 43210",
    shopId: "shop-city-copy",
    shopName: "City Copy Point",
    documents: [
      { id: "doc-011", name: "Certificate.pdf", pages: 1, sizeMb: 0.2 },
    ],
    config: {
      paperTypeId: "a4",
      printType: "color",
      side: "single",
      copies: 5,
      pageRangeMode: "all",
      pageRange: "",
      orientation: "landscape",
      bindingId: null,
      additionalIds: ["lamination"],
    },
    configLabels: {
      paper: "A4 Paper",
      printType: "Colour",
      side: "Single Side",
      orientation: "Landscape",
      binding: "None",
      additional: ["Lamination"],
    },
    fulfillment: "pickup",
    address: null,
    price: {
      printing: 40,
      binding: 0,
      services: 50,
      delivery: 0,
      discount: 0,
      total: 90,
      billablePages: 5,
    },
    paymentMethod: "full",
    amountPaid: 90,
    balance: 0,
    paymentStatus: "paid",
    status: "COMPLETED",
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
    timeline: [
      { status: "NEW", at: daysAgo(7) },
      { status: "ACCEPTED", at: daysAgo(7) },
      { status: "PRINTING", at: daysAgo(7) },
      { status: "FINISHING", at: daysAgo(7) },
      { status: "READY_PICKUP", at: daysAgo(7) },
      { status: "COMPLETED", at: daysAgo(7) },
    ],
  },
  {
    id: "OMX-1011",
    customerName: "Tamil Kumaran",
    customerPhone: "+91 98765 43210",
    shopId: "shop-tamil-printers",
    shopName: "Tamil Printers",
    documents: [
      { id: "doc-012", name: "Meeting-Minutes.pdf", pages: 6, sizeMb: 0.8 },
    ],
    config: {
      paperTypeId: "bond",
      printType: "bw",
      side: "double",
      copies: 3,
      pageRangeMode: "all",
      pageRange: "",
      orientation: "portrait",
      bindingId: "spiral",
      additionalIds: [],
    },
    configLabels: {
      paper: "Bond Sheet",
      printType: "Black & White",
      side: "Double Side",
      orientation: "Portrait",
      binding: "Spiral Binding",
      additional: [],
    },
    fulfillment: "pickup",
    address: null,
    price: {
      printing: 36,
      binding: 120,
      services: 0,
      delivery: 0,
      discount: 10,
      total: 146,
      billablePages: 18,
    },
    paymentMethod: "full",
    amountPaid: 146,
    balance: 0,
    paymentStatus: "paid",
    status: "COMPLETED",
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
    timeline: [
      { status: "NEW", at: daysAgo(10) },
      { status: "ACCEPTED", at: daysAgo(10) },
      { status: "PRINTING", at: daysAgo(10) },
      { status: "FINISHING", at: daysAgo(10) },
      { status: "READY_PICKUP", at: daysAgo(10) },
      { status: "COMPLETED", at: daysAgo(10) },
    ],
  },
  {
    id: "OMX-1012",
    customerName: "Tamil Kumaran",
    customerPhone: "+91 98765 43210",
    shopId: "shop-kumar-xerox",
    shopName: "Kumar Xerox & Stationery",
    documents: [
      { id: "doc-013", name: "Assignment.pdf", pages: 15, sizeMb: 2.4 },
      { id: "doc-014", name: "Lab-Record.pdf", pages: 28, sizeMb: 3.2 },
    ],
    config: {
      paperTypeId: "a4",
      printType: "bw",
      side: "single",
      copies: 1,
      pageRangeMode: "all",
      pageRange: "",
      orientation: "portrait",
      bindingId: null,
      additionalIds: [],
    },
    configLabels: {
      paper: "A4 Paper",
      printType: "Black & White",
      side: "Single Side",
      orientation: "Portrait",
      binding: "None",
      additional: [],
    },
    fulfillment: "pickup",
    address: null,
    price: {
      printing: 43,
      binding: 0,
      services: 0,
      delivery: 0,
      discount: 0,
      total: 43,
      billablePages: 43,
    },
    paymentMethod: "cash_pickup",
    amountPaid: 0,
    balance: 43,
    paymentStatus: "unpaid",
    status: "REJECTED",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    timeline: [
      { status: "NEW", at: daysAgo(2) },
      { status: "REJECTED", at: daysAgo(2) },
    ],
  },
];

export const demoReviews: Review[] = [
  {
    id: "rev-001",
    orderId: "OMX-1009",
    shopId: "shop-tamil-printers",
    customerId: "acc-customer-1",
    customerName: "Tamil Kumaran",
    rating: 5,
    description: "Excellent photo prints, vibrant colors and sharp detail. Very happy with the quality.",
    createdAt: daysAgo(2),
  },
  {
    id: "rev-002",
    orderId: "OMX-1005",
    shopId: "shop-tamil-printers",
    customerId: "acc-customer-1",
    customerName: "Tamil Kumaran",
    rating: 4,
    description: "Good quality hard binding for my thesis. Slightly delayed but overall satisfied.",
    createdAt: daysAgo(1),
  },
  {
    id: "rev-003",
    orderId: "OMX-1001",
    shopId: "shop-tamil-printers",
    customerId: "acc-customer-1",
    customerName: "Tamil Kumaran",
    rating: 5,
    description: "Quick service, good quality prints. Spiral binding was neat and clean.",
    createdAt: daysAgo(4),
  },
  {
    id: "rev-004",
    orderId: "OMX-1010",
    shopId: "shop-city-copy",
    customerId: "acc-customer-1",
    customerName: "Tamil Kumaran",
    rating: 5,
    description: "Perfect lamination on certificates. Very professional finish. Will order again.",
    createdAt: daysAgo(6),
  },
  {
    id: "rev-005",
    orderId: "OMX-1004",
    shopId: "shop-sri-lakshmi",
    customerId: "acc-customer-1",
    customerName: "Tamil Kumaran",
    rating: 4,
    description: "Decent printing speed. Lab records came out well with spiral binding.",
    createdAt: daysAgo(5),
  },
  {
    id: "rev-006",
    orderId: "OMX-1011",
    shopId: "shop-tamil-printers",
    customerId: "acc-customer-1",
    customerName: "Tamil Kumaran",
    rating: 3,
    description: "Print quality was okay but had to wait longer than expected for pickup.",
    createdAt: daysAgo(9),
  },
  {
    id: "rev-007",
    orderId: "OMX-1006",
    shopId: "shop-psg-print",
    customerId: "acc-customer-1",
    customerName: "Tamil Kumaran",
    rating: 5,
    description: "Color prints were brilliant. Delivery was on time to my college address.",
    createdAt: daysAgo(3),
  },
  {
    id: "rev-008",
    orderId: "OMX-1008",
    shopId: "shop-smart-print",
    customerId: "acc-customer-1",
    customerName: "Tamil Kumaran",
    rating: 2,
    description: "Had to wait longer than expected. The invoice print had a slight smudge.",
    createdAt: daysAgo(6),
  },
  {
    id: "rev-009",
    orderId: "OMX-1002",
    shopId: "shop-campus-copy",
    customerId: "acc-customer-1",
    customerName: "Tamil Kumaran",
    rating: 5,
    description: "Soft binding for project report was top-notch. Colors were accurate on every page.",
    createdAt: daysAgo(4),
  },
  {
    id: "rev-010",
    orderId: "OMX-1007",
    shopId: "shop-tamil-printers",
    customerId: "acc-customer-1",
    customerName: "Tamil Kumaran",
    rating: 1,
    description: "Very disappointed. Pages were slightly misaligned in the spiral binding and some text was cut off.",
    createdAt: daysAgo(3),
  },
];

export const demoNotifications: Notification[] = [
  {
    id: "notif-001",
    recipientId: "acc-customer-1",
    recipientRole: "customer",
    type: "order_placed",
    title: "Order Placed",
    message: "Your order OMX-1001 has been placed successfully at Tamil Printers.",
    relatedEntityId: "OMX-1001",
    entityType: "order",
    read: true,
    createdAt: ago(12),
  },
  {
    id: "notif-002",
    recipientId: "acc-customer-1",
    recipientRole: "customer",
    type: "order_placed",
    title: "Order Placed",
    message: "Your order OMX-1002 has been placed successfully at Campus Copy Centre.",
    relatedEntityId: "OMX-1002",
    entityType: "order",
    read: true,
    createdAt: ago(90),
  },
  {
    id: "notif-003",
    recipientId: "acc-customer-1",
    recipientRole: "customer",
    type: "order_accepted",
    title: "Order Accepted",
    message: "Your order OMX-1002 has been accepted by Campus Copy Centre.",
    relatedEntityId: "OMX-1002",
    entityType: "order",
    read: true,
    createdAt: ago(75),
  },
  {
    id: "notif-004",
    recipientId: "acc-customer-1",
    recipientRole: "customer",
    type: "printing_started",
    title: "Printing Started",
    message: "Printing has started for your order OMX-1003 at Tamil Printers.",
    relatedEntityId: "OMX-1003",
    entityType: "order",
    read: false,
    createdAt: ago(120),
  },
  {
    id: "notif-005",
    recipientId: "acc-customer-1",
    recipientRole: "customer",
    type: "printing_completed",
    title: "Printing Completed",
    message: "Printing for order OMX-1004 is complete. Finishing in progress.",
    relatedEntityId: "OMX-1004",
    entityType: "order",
    read: false,
    createdAt: ago(150),
  },
  {
    id: "notif-006",
    recipientId: "acc-customer-1",
    recipientRole: "customer",
    type: "ready_pickup",
    title: "Ready for Pickup",
    message: "Your order OMX-1005 is ready for pickup at Tamil Printers.",
    relatedEntityId: "OMX-1005",
    entityType: "order",
    read: false,
    createdAt: ago(60),
  },
  {
    id: "notif-007",
    recipientId: "acc-customer-1",
    recipientRole: "customer",
    type: "out_for_delivery",
    title: "Out for Delivery",
    message: "Your order OMX-1007 is out for delivery to your home address.",
    relatedEntityId: "OMX-1007",
    entityType: "order",
    read: false,
    createdAt: ago(20),
  },
  {
    id: "notif-008",
    recipientId: "acc-customer-1",
    recipientRole: "customer",
    type: "delivered",
    title: "Delivered",
    message: "Your order OMX-1008 has been delivered to your office address.",
    relatedEntityId: "OMX-1008",
    entityType: "order",
    read: true,
    createdAt: ago(1000),
  },
  {
    id: "notif-009",
    recipientId: "acc-customer-1",
    recipientRole: "customer",
    type: "payment_update",
    title: "Payment Received",
    message: "Payment of Rs. 816 received for order OMX-1002. Full payment confirmed.",
    relatedEntityId: "OMX-1002",
    entityType: "order",
    read: true,
    createdAt: ago(74),
  },
  {
    id: "notif-010",
    recipientId: "acc-customer-1",
    recipientRole: "customer",
    type: "payment_update",
    title: "Partial Payment",
    message: "Partial payment of Rs. 360 received for order OMX-1006. Balance of Rs. 840 due.",
    relatedEntityId: "OMX-1006",
    entityType: "order",
    read: false,
    createdAt: ago(379),
  },
  {
    id: "notif-011",
    recipientId: "acc-customer-1",
    recipientRole: "customer",
    type: "review_received",
    title: "Review Thank You",
    message: "Thank you for reviewing your order at Tamil Printers. Your feedback helps us improve.",
    relatedEntityId: "rev-001",
    entityType: "review",
    read: true,
    createdAt: daysAgo(2),
  },
  {
    id: "notif-012",
    recipientId: "acc-customer-1",
    recipientRole: "customer",
    type: "order_status_changed",
    title: "Order Status Updated",
    message: "Your order OMX-1006 status has been updated to Ready for Delivery.",
    relatedEntityId: "OMX-1006",
    entityType: "order",
    read: true,
    createdAt: ago(80),
  },
  {
    id: "notif-013",
    recipientId: "acc-customer-1",
    recipientRole: "customer",
    type: "order_placed",
    title: "Order Placed",
    message: "Your order OMX-1012 has been placed at Campus Copy Centre.",
    relatedEntityId: "OMX-1012",
    entityType: "order",
    read: true,
    createdAt: daysAgo(2),
  },
  {
    id: "notif-014",
    recipientId: "acc-customer-1",
    recipientRole: "customer",
    type: "order_rejected",
    title: "Order Rejected",
    message: "Your order OMX-1012 was rejected by Campus Copy Centre. Please contact support for details.",
    relatedEntityId: "OMX-1012",
    entityType: "order",
    read: false,
    createdAt: daysAgo(2),
  },
  {
    id: "notif-015",
    recipientId: "acc-customer-1",
    recipientRole: "customer",
    type: "ready_pickup",
    title: "Ready for Delivery",
    message: "Your order OMX-1006 is ready for delivery from PSG Print Hub.",
    relatedEntityId: "OMX-1006",
    entityType: "order",
    read: true,
    createdAt: ago(90),
  },
  {
    id: "notif-101",
    recipientId: "acc-shop-1",
    recipientRole: "shopkeeper",
    type: "order_placed",
    title: "New Order Received",
    message: "New order OMX-1001 placed by Tamil Kumaran for 2 copies of Assignment.pdf.",
    relatedEntityId: "OMX-1001",
    entityType: "order",
    read: true,
    createdAt: ago(12),
  },
  {
    id: "notif-102",
    recipientId: "acc-shop-1",
    recipientRole: "shopkeeper",
    type: "order_placed",
    title: "New Order Received",
    message: "New order OMX-1003 placed by Tamil Kumaran for 3 copies of ID-Proof.pdf.",
    relatedEntityId: "OMX-1003",
    entityType: "order",
    read: true,
    createdAt: ago(180),
  },
  {
    id: "notif-103",
    recipientId: "acc-shop-1",
    recipientRole: "shopkeeper",
    type: "order_accepted",
    title: "Order Accepted",
    message: "You accepted order OMX-1003. Please proceed with printing.",
    relatedEntityId: "OMX-1003",
    entityType: "order",
    read: true,
    createdAt: ago(165),
  },
  {
    id: "notif-104",
    recipientId: "acc-shop-1",
    recipientRole: "shopkeeper",
    type: "payment_update",
    title: "Payment Received",
    message: "Full payment of Rs. 134 received for order OMX-1001.",
    relatedEntityId: "OMX-1001",
    entityType: "order",
    read: false,
    createdAt: ago(11),
  },
  {
    id: "notif-105",
    recipientId: "acc-shop-1",
    recipientRole: "shopkeeper",
    type: "review_received",
    title: "New Review",
    message: "Tamil Kumaran left a 5-star review for your order OMX-1009.",
    relatedEntityId: "rev-001",
    entityType: "review",
    read: false,
    createdAt: daysAgo(2),
  },
  {
    id: "notif-106",
    recipientId: "acc-shop-1",
    recipientRole: "shopkeeper",
    type: "review_received",
    title: "New Review",
    message: "Tamil Kumaran left a 1-star review for your order OMX-1007. Please look into this.",
    relatedEntityId: "rev-010",
    entityType: "review",
    read: false,
    createdAt: daysAgo(3),
  },
  {
    id: "notif-107",
    recipientId: "acc-shop-1",
    recipientRole: "shopkeeper",
    type: "order_placed",
    title: "New Order Received",
    message: "New order OMX-1005 placed by Tamil Kumaran for Thesis-Chapter1.pdf with hard binding.",
    relatedEntityId: "OMX-1005",
    entityType: "order",
    read: true,
    createdAt: ago(500),
  },
  {
    id: "notif-108",
    recipientId: "acc-shop-1",
    recipientRole: "shopkeeper",
    type: "order_placed",
    title: "New Order Received",
    message: "New order OMX-1007 placed by Tamil Kumaran for delivery.",
    relatedEntityId: "OMX-1007",
    entityType: "order",
    read: true,
    createdAt: ago(240),
  },
  {
    id: "notif-109",
    recipientId: "acc-shop-1",
    recipientRole: "shopkeeper",
    type: "payment_update",
    title: "Payment Received",
    message: "Full payment of Rs. 480 received for order OMX-1009.",
    relatedEntityId: "OMX-1009",
    entityType: "order",
    read: true,
    createdAt: daysAgo(3),
  },
  {
    id: "notif-110",
    recipientId: "acc-shop-1",
    recipientRole: "shopkeeper",
    type: "order_placed",
    title: "New Order Received",
    message: "New order OMX-1011 placed by Tamil Kumaran for Bond Sheet printing.",
    relatedEntityId: "OMX-1011",
    entityType: "order",
    read: true,
    createdAt: daysAgo(10),
  },
];

export const demoTickets: SupportTicket[] = [
  {
    id: "ticket-001",
    subject: "Print quality issue",
    orderId: "OMX-1007",
    category: "Quality",
    description: "The spiral binding on order OMX-1007 was misaligned and some text on the edges was cut off. I would like a reprint or refund for this order.",
    createdAt: daysAgo(3),
    status: "open",
  },
  {
    id: "ticket-002",
    subject: "Delivery delay",
    orderId: "OMX-1008",
    category: "Delivery",
    description: "Order OMX-1008 was supposed to be delivered within 45 minutes but it took over 2 hours. The delivery agent could not find the address even though it was clearly mentioned.",
    createdAt: daysAgo(6),
    status: "resolved",
  },
  {
    id: "ticket-003",
    subject: "Payment not reflected",
    orderId: undefined,
    category: "Payment",
    description: "I made a UPI payment of Rs. 816 for order OMX-1002 but the app still shows pending. The transaction ID is TXN123456789. Please verify and update the status.",
    createdAt: daysAgo(7),
    status: "open",
  },
];

export const demoShopkeeperApplications: ShopApplication[] = [
  {
    id: "app-001",
    accountId: "acc-shop-1",
    shopkeeperProfile: {
      accountId: "acc-shop-1",
      username: "rameshkumar_tp",
      ownerName: "Ramesh Kumar",
      phone: "+91 98431 22100",
      alternatePhone: "+91 98431 22101",
    },
    shopName: "Tamil Printers",
    shopAddress: "12, Gandhi Street, Gandhipuram",
    area: "Gandhipuram",
    city: "Coimbatore",
    state: "Tamil Nadu",
    pincode: "641012",
    whatsappNumber: "+91 98431 22100",
    shopDescription: "Professional print shop in Gandhipuram offering B&W and color printing, binding, and lamination services. Serving students and businesses since 2010.",
    shopImages: [
      { id: "si-001", imageUrl: "", imageType: "front", sortOrder: 0 },
      { id: "si-002", imageUrl: "", imageType: "interior", sortOrder: 1 },
    ],
    services: {
      a4: true,
      a3: true,
      bondSheet: true,
      photoSheet: true,
      bw: true,
      colour: true,
      pickup: true,
      delivery: true,
      deliveryFee: 30,
      businessHoursFrom: "08:00",
      businessHoursTo: "21:00",
      workingDays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    },
    accountStatus: "active",
    createdAt: daysAgo(60),
    updatedAt: daysAgo(55),
  },
  {
    id: "app-002",
    accountId: "acc-shop-9",
    shopkeeperProfile: {
      accountId: "acc-shop-9",
      username: "venkatesh_vp",
      ownerName: "Venkatesh Prasad",
      phone: "+91 94432 66770",
      alternatePhone: "+91 94432 66771",
    },
    shopName: "Venkatesh Print World",
    shopAddress: "89, Mettupalayam Road",
    area: "Avinashi Road",
    city: "Coimbatore",
    state: "Tamil Nadu",
    pincode: "641045",
    whatsappNumber: "+91 94432 66770",
    shopDescription: "New print shop offering affordable printing services with quick turnaround. Specializing in large format and photo printing.",
    shopImages: [
      { id: "si-003", imageUrl: "", imageType: "front", sortOrder: 0 },
      { id: "si-004", imageUrl: "", imageType: "counter", sortOrder: 1 },
    ],
    services: {
      a4: true,
      a3: true,
      bondSheet: false,
      photoSheet: true,
      bw: true,
      colour: true,
      pickup: true,
      delivery: false,
      deliveryFee: 0,
      businessHoursFrom: "09:00",
      businessHoursTo: "20:00",
      workingDays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    },
    accountStatus: "pending",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
];

export const demoShopkeeperProfiles: Record<string, ShopkeeperProfile> = {
  "acc-shop-1": {
    accountId: "acc-shop-1",
    username: "rameshkumar_tp",
    ownerName: "Ramesh Kumar",
    phone: "+91 98431 22100",
    alternatePhone: "+91 98431 22101",
  },
  "acc-shop-2": {
    accountId: "acc-shop-2",
    username: "lakshminarayanan_ap",
    ownerName: "Lakshmi Narayanan",
    phone: "+91 99406 78110",
    alternatePhone: "+91 99406 78111",
  },
  "acc-shop-3": {
    accountId: "acc-shop-3",
    username: "arunprasad_cc",
    ownerName: "Arun Prasad",
    phone: "+91 90035 41266",
    alternatePhone: "+91 90035 41268",
  },
  "acc-shop-4": {
    accountId: "acc-shop-4",
    username: "lakshmidevi_sl",
    ownerName: "Lakshmi Devi",
    phone: "+91 98765 11110",
    alternatePhone: "+91 98765 11112",
  },
  "acc-shop-5": {
    accountId: "acc-shop-5",
    username: "rajeshkumar_cp",
    ownerName: "Rajesh Kumar",
    phone: "+91 99876 22221",
    alternatePhone: "+91 99876 22223",
  },
  "acc-shop-6": {
    accountId: "acc-shop-6",
    username: "anandprasad_pg",
    ownerName: "Anand Prasad",
    phone: "+91 97654 33332",
    alternatePhone: "+91 97654 33334",
  },
  "acc-shop-7": {
    accountId: "acc-shop-7",
    username: "kumaravel_kx",
    ownerName: "Kumaravel",
    phone: "+91 96543 44443",
    alternatePhone: "+91 96543 44445",
  },
  "acc-shop-8": {
    accountId: "acc-shop-8",
    username: "senthilmurugan_sp",
    ownerName: "Senthil Murugan",
    phone: "+91 95432 55554",
    alternatePhone: "+91 95432 55556",
  },
};
