/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderRouteImport } from './routes/order'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupportRouteImport } from './routes/support'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopOrdersRouteImport } from './routes/shop.orders'
import { Route as ShopProfileRouteImport } from './routes/shop.profile'
import { Route as ShopServicesRouteImport } from './routes/shop.services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopOrdersRoute = ShopOrdersRouteImport.update({
  id: '/shop/orders',
  path: '/shop/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProfileRoute = ShopProfileRouteImport.update({
  id: '/shop/profile',
  path: '/shop/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopServicesRoute = ShopServicesRouteImport.update({
  id: '/shop/services',
  path: '/shop/services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/order': typeof OrderRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/shop/profile': typeof ShopProfileRoute
  '/shop/services': typeof ShopServicesRoute
  '/orders/': typeof OrdersIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/order': typeof OrderRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/shop/profile': typeof ShopProfileRoute
  '/shop/services': typeof ShopServicesRoute
  '/orders': typeof OrdersIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/order': typeof OrderRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/shop/profile': typeof ShopProfileRoute
  '/shop/services': typeof ShopServicesRoute
  '/orders/': typeof OrdersIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/order'
    | '/profile'
    | '/settings'
    | '/support'
    | '/orders/$orderId'
    | '/shop/orders'
    | '/shop/profile'
    | '/shop/services'
    | '/orders/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/order'
    | '/profile'
    | '/settings'
    | '/support'
    | '/orders/$orderId'
    | '/shop/orders'
    | '/shop/profile'
    | '/shop/services'
    | '/orders'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/order'
    | '/profile'
    | '/settings'
    | '/support'
    | '/orders/$orderId'
    | '/shop/orders'
    | '/shop/profile'
    | '/shop/services'
    | '/orders/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrderRoute: typeof OrderRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ShopOrdersRoute: typeof ShopOrdersRoute
  ShopProfileRoute: typeof ShopProfileRoute
  ShopServicesRoute: typeof ShopServicesRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/orders': {
      id: '/shop/orders'
      path: '/shop/orders'
      fullPath: '/shop/orders'
      preLoaderRoute: typeof ShopOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/profile': {
      id: '/shop/profile'
      path: '/shop/profile'
      fullPath: '/shop/profile'
      preLoaderRoute: typeof ShopProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/services': {
      id: '/shop/services'
      path: '/shop/services'
      fullPath: '/shop/services'
      preLoaderRoute: typeof ShopServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrderRoute: OrderRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ShopOrdersRoute: ShopOrdersRoute,
  ShopProfileRoute: ShopProfileRoute,
  ShopServicesRoute: ShopServicesRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
